-- CreateTable
CREATE TABLE "HitTrax" (
    "id" SERIAL NOT NULL,
    "sessionId" TEXT NOT NULL,
    "athlete" TEXT,
    "AB" INTEGER,
    "date" TEXT,
    "timestamp" TEXT,
    "pitch" DOUBLE PRECISION,
    "strikeZone" TEXT,
    "pType" TEXT,
    "velo" DOUBLE PRECISION,
    "LA" DOUBLE PRECISION,
    "dist" DOUBLE PRECISION,
    "res" TEXT,
    "type" TEXT,
    "horizAngle" DOUBLE PRECISION,
    "pts" DOUBLE PRECISION,
    "strikeZoneBottom" DOUBLE PRECISION,
    "strikeZoneTop" DOUBLE PRECISION,
    "strikeZoneWidth" DOUBLE PRECISION,
    "verticalDistance" DOUBLE PRECISION,
    "horizontalDistance" DOUBLE PRECISION,
    "POIX" DOUBLE PRECISION,
    "POIY" DOUBLE PRECISION,
    "POIZ" DOUBLE PRECISION,
    "sprayChartX" DOUBLE PRECISION,
    "sprayChartZ" DOUBLE PRECISION,
    "fieldedX" DOUBLE PRECISION,
    "fieldedZ" DOUBLE PRECISION,
    "batMaterial" TEXT,
    "user" TEXT,
    "pitchAngle" DOUBLE PRECISION,
    "batting" TEXT,
    "level" TEXT,
    "opposingPlayer" TEXT,
    "tag" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HitTrax_pkey" PRIMARY KEY ("id")
);
