import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import "./globals.css";
import SignInPrompt from "@/components/SignInPrompt";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="h-screen w-screen flex flex-col">
          {/* Fixed Navbar */}
          <Navbar />
          {/* Main Content */}
          <SignedIn>
            <div className="flex-1 overflow-y-auto">{children}</div>
          </SignedIn>
          <SignedOut>
            <SignInPrompt />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
