import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import "./globals.css";
import SignInPrompt from "@/components/SignInPrompt";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* 
          Using min-h-screen makes the body at least the viewport height,
          and flex + flex-col + overflow-y-auto let the page scroll 
          if content is longer than the screen. 
        */}
        <body className="min-h-screen w-screen flex flex-col overflow-y-auto">
          {/* Fixed Navbar at the top */}
          <Navbar />

          {/* 
            Main content:
            - SignedIn: shows the actual page content if the user is signed in
            - SignedOut: shows the sign-in prompt otherwise
          */}
          <SignedIn>
            <div className="flex-1 overflow-y-auto">{children}</div>
          </SignedIn>
          <SignedOut>
            <SignInPrompt />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
